dist: xenial
language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
install:
  - pip install -r requirements.txt
script:
  - pytest
  - mypy --strict
    common.py
    entities/*.py
    dfn_configs.py
    generate_connectors.py
    generate_chip.py
    generate_mosfet_dual.py
    generate_so.py
    generate_dip.py
  - mypy --check-untyped-defs --warn-return-any
    test_entities.py
    generate_qfp.py
    #generate_dfn.py
    #test_common.py
    #test_generate_connectors.py
    #test_generate_qfn.py
